### ISSUE TITLE
Docker: distant mysql issue connecting

### ISSUE THREAD

**Issue by julien-vu** [danielbrendel/hortusfox-web#104]
Hi, I use another docker container for Mysql: 10.0.0.5 on port 3306, cant connect to it from the project: 10.0.0.5 port 8080

Only message I got is 
Waiting for database to be available...

**Comment by danielbrendel** [comment]
Hi, what are your modifications in the related docker files/scripts?

**Comment by julien-vu** [comment]
I modified:

DB_HOST: 10.0.0.15
DB_PORT: 3306
DB_DATABASE: hortusfox
DB_USERNAME: hortusfox
DB_USER: hortusfox
DB_PASSWORD: hortusfox

everything else is the same

**Comment by danielbrendel** [comment]
Why are you trying to use a custom mysql container? Because there is one already included.

**Comment by julien-vu** [comment]
I'm using it in unraid so not pulling from github and using a distant DB

**Comment by Whatsek** [comment]
I have had the same experience with an external myswl database. I am trying to install hortus-web on my Synology with the built in MariaDB. (As I do with a lot of other dockers) I also couldnt connect to the database, same error: Waiting for database to be available...

Will try to install this again when I have more time....

**Comment by danielbrendel** [comment]
It depends on your system environment. Is your external mariadb on the same host machine? Then you need to figure out the host IP address and be sure that the ports do not interfere with the db container. In my case on Windows I do:
```yml
DB_HOST: host.docker.internal
```
If you use another server then you need to know the IP and be sure you can connect to it from your host and app container. I don't have an external server available right now in order to test. Also I am not sure if you'd need to adjust [network_mode](https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode).

**Comment by julien-vu** [comment]
Back after some look into the codebase:

https://github.com/danielbrendel/hortusfox-web/blob/main/docker-entrypoint.sh

in the entrypoint you never set the DB_PORT in those queries, might be a project wide issue and the reason why it cant connect.

I am using the port 3313 not the default one.

**Comment by danielbrendel** [comment]
Hi, I tried to change the port myself in the docker-compose file and it doesn't work. Specifying the port is missing in the entry point script. Will be fixed within the next version. Thank you for your report!

**Comment by danielbrendel** [comment]
Uh, I forgot this in the current release. My apologies. I'll priorize this.

**Comment by danielbrendel** [comment]
Does it now work on your end @julien-vu ?

**Comment by danielbrendel** [comment]
Hi

No, 2.5 was not released yet. It might take a while because I am considering to implement an issue that could take a bit longer. But if you want, you can pull from the main branch and try it out. This way we can check if it works and if not I can provide a fix. 

Not sure if 2.5 will be released this month, but I am very sure April will fit for a possible release.

**Comment by danielbrendel** [comment]
Resolved.
