### ISSUE TITLE
[Feature Requests] Plant attributes & Settings

### ISSUE THREAD

**Issue by HerrTim** [danielbrendel/hortusfox-web#136]
Hello,
after I can use it now, I have some suggestions for you :)

**Plant attributes**
*Cutting month*
Add multi select for the cutting month at the plant attributes, as it is not always only one month.
Add a dashboard / view on monthly basis for the cutting month. This way you can identify really fast, if a plant needs to be cut.

*Notes*
Add a multiline or possibility to use html code e.g. < br >, < a href >, etc.

*Fertilizer*
Add input for fertilizer information, e.g. month, text for details.
Add a dashboard / view on monthly basis for fertilizer.

**Settings**
*User*
It is possible to add a user without a email syntax (...@...). This causes problems afterwards but it should be forbidden during creation process.

*Menu*
Add feature to edit the menu. I assume the existing menu for tasks and inventory is not usefull for everybody. A dashboard / view for cutting month / fertilizer month / overview of all plants will be a good feature. A simple checkbox menu in settings to enable / disable the menu points will be a good feature for the start.

That's it for today :)
Overall it's a great tool, keep on going! Thank you for your time & work.

**Comment by danielbrendel** [comment]
Hi, thank you for your feedback!

- Cutting month: That's a nice suggestion. It could be done so that the dashboard shows all upcoming cuttings? Like for the next month. Would that be sufficient?
- Notes: You're right, multiline is better for notes. Will be added in the next version.
- Fertilizer: True, that's currently missing. Will be added.

- User E-Mail: Just tested it, you're right. Will be fixed.
- Menu: Do you mean the bottom navigation menu? Or which menu specifically?

Glad you like the tool. Thank you for the detailed feedback. :)

**Comment by HerrTim** [comment]
Hi @danielbrendel,

- Cutting month: I would create two pages, one for cutting month and one fertilizer. The pages would show an annual calendar with the plants for each month. In addition show the upcoming cuttings and fertilizer actions for the next month.
- Menu: I thought about putting the page names, e.g. Tasks, Inventory, etc. with checkboxes on the settings page. When the checkbox is checked, the page is shown/visible in the top menu. When a page is not checked, it's invisible in the menu. The same principle could be done with the content of the dashboard.

**Comment by danielbrendel** [comment]
Ah, now I get what you mean. I'll plan this for one of the next versions.

**Comment by HerrTim** [comment]
Great :) You could also think of a notification for cutting and fertilizing, e.g. sending a mail with upcoming actions, x days before the current month ends.

**Comment by HerrTim** [comment]
Hello @danielbrendel,
I've noticed you've added the calendar as experimental. Great feature :)
What's your plan? Will you link the calender entries with the plant attributes to reduce multiple data input and administration?

**Comment by danielbrendel** [comment]
Hi @HerrTim 
Thank you. :)
Yes, this would be the way to go. And other things. Currently it's a gantt style chart and I am not sure if this is sufficient. What's your opinion about that? 
There need some more things to be done with the calendar feature (like recurring dates, evaluating whether tasks should be connected, too, etc.). 

I think after all we're heading right to v3.0 here. Tho the next version will take a bit longer, because I also want to get familiar with plant APIs like trefle.
