### ISSUE TITLE
[Bug] Add plant

### ISSUE THREAD

**Issue by HerrTim** [danielbrendel/hortusfox-web#144]
I tried to add a new plant and received an error 500.

Installed version: 2.4
![Screenshot 2024-03-16 221457](https://github.com/danielbrendel/hortusfox-web/assets/26392599/b1d2978e-84e7-4603-be5f-b335414268fc)

**Comment by danielbrendel** [comment]
Ah, yeah, the following columns of the PlantsModel table were modified in the last release:
```sql
perennial BOOLEAN NULL
humidity INT NULL
light_level VARCHAR(512) NULL
```
The problem here is that your actual table still does have these columns as mandatory (NOT NULL). 

You can change these columns in your database container. If you need help I can assist you with this. :) 
_Note to myself:_ Implement that proper database migration for version updates.

**Comment by danielbrendel** [comment]
Will be continued in #145
