### ISSUE TITLE
What is the easiest way to test Master branch updates

### ISSUE THREAD

**Issue by tomduud** [danielbrendel/hortusfox-web#169]
With the normal dockerized installation, what would be the easiest way to test new commits/features added in to repository without Development environment if there is a such possibility? (e.g. keeping the current database?). And what would be the update path once new version is released?

**Comment by danielbrendel** [comment]
In general you should not mix your prod env with a test env. I recommend
setting up a second test env with a bit of test data. Like a playground to
test things without the dangers of experiencing data loss or any other
unexpected behaviour.

If you want to fetch from main branch you'd have to build the image
yourself because the workflow does only trigger the build action on new
versions or the beta version (which has to be created manually for now)

Upgrading to a new prod image version should be straight forward via
`docker-compose pull` and `docker-compose up -d`. This should fetch the new
version from ghcr and recreate everything updated.
