### ISSUE TITLE
Plant added, but app is empty

### ISSUE THREAD

**Issue by lockheed** [danielbrendel/hortusfox-web#187]
**Describe the bug**
After adding a plant, the app still shows as empty. Plant is only accessible by searching by name.

**Screenshots**
![image](https://github.com/danielbrendel/hortusfox-web/assets/3472480/dcce2e53-8521-41f7-9206-969e023d9f37)
![image](https://github.com/danielbrendel/hortusfox-web/assets/3472480/94e9d280-9033-4906-bbcf-8c01e81d9137)
![image](https://github.com/danielbrendel/hortusfox-web/assets/3472480/916111f3-8c44-47e3-ab4e-6f6417044e6b)

**Desktop (please complete the following information):**
 - OS: Arch
 - Browser firefox

**Additional context**

**Comment by danielbrendel** [comment]
Hi, what HortusFox and PHP version are you using? Do you use it in a docker environment? If so, did you make any changes to the docker files?

**Comment by lockheed** [comment]
Latest docker image. The only thing edited is my [docker-compose](https://pastebin.com/raw/ktaQjnBd)

**Comment by danielbrendel** [comment]
That is a complete different docker-compose file from a different app.

> Latest docker image. The only thing edited is my docker-compose
> <https://pastebin.com/raw/ktaQjnBd>
>

**Comment by lockheed** [comment]
Sorry, my mistake. Here's [the right one](https://pastebin.com/raw/sLZnYJ5n).

**Comment by lockheed** [comment]
Any ideas @danielbrendel ?

**Comment by danielbrendel** [comment]
Hi, sorry, I didn't find the time to look further earlier.

The issue seems odd at first, but I can see from your log history that you
moved the plant to your history section.

Plants that are marked historical are not shown in locations or recent
plants list. Keep in mind that plants should only be moved there when they
are gone but you want to keep them anyway to dwell in memories of your past
plants. So, alive plants do not belong there.

Fix: Go to your history section and restore your plant from there.

**Comment by lockheed** [comment]
Ah, I though "History" means the "log" for the plant, i.e. date of purchase, history of disease, important events etc. Is there such a functionality in Hortusfox?

**Comment by danielbrendel** [comment]
Not yet, but it is planned for v3.1 via issue #156

**Comment by danielbrendel** [comment]
I'll close this issue for now since it is resolved.
