### ISSUE TITLE
500 Internal Server Error - After upgrade to 3.1

### ISSUE THREAD

**Issue by chiruleonard** [danielbrendel/hortusfox-web#213]
**Describe the bug**
I used the docker instructions from the github page. https://github.com/danielbrendel/hortusfox-web?tab=readme-ov-file#installation but when i tried to access the app, username and password was ok, but once i click Login it gave me this error.

**Screenshots and Logs**
[Screenshot](https://imgur.com/UjBLGTv)
[Logs](https://pastebin.com/raw/QgtjBF2i)

**Software:**
- HortusFox version 3.1
- PHP Version: PHP 8.2.0
- MySQL version: Ver 15.1 Distrib 10.5.23-MariaDB
- Docker version: docker-compose version 1.29.2

**Comment by danielbrendel** [comment]
Hi,

The error is caused because there is at least one recent log entry in the
`log` table associated with a non existing user.

A workaround would be to identify the user id and clear all log entries of
that user. Or clear the entire log table.
You could also manually edit the /app/models/LogModel.php file and validate
that $log_user is not null at line 51.

Those are the only solutions right now until I add a fix.

Sorry for the inconvenience. If you need help with that workarounds feel
free to join the discord and msg me there.

Kind Regards

chiruleonard ***@***.***> schrieb am Fr., 24. Mai 2024, 15:25:

**Comment by danielbrendel** [comment]
Hi,

The error is caused because there is at least one recent log entry in the
`log` table associated with a non existing user.

A workaround would be to identify the user id and clear all log entries of
that user. Or clear the entire log table.
You could also manually edit the /app/models/LogModel.php file and validate
that $log_user is not null at line 51.

Those are the only solutions right now until I add a fix.

Sorry for the inconvenience. If you need help with that workarounds feel
free to join the discord and msg me there.

Kind Regards
