### ISSUE TITLE
Feature Request : Global Fonts

### ISSUE THREAD

**Issue by kaleben0** [danielbrendel/hortusfox-web#289]
**Description of your request**
The ability to choose from a selection of fonts (Google Fonts has many) and would override the default font and fonts that come with themes. 

**Describe the solution you'd like**
Just an drop down in the Admin controls to select a new font option

**Comment by danielbrendel** [comment]
Hi,

unfortunately this will not work. Each font has their own specific sizes
and dimensions of the characters. So, while font A works flawlessly, Font B
will break many elements. Sometimes adjusting the font base size will
suffice, but other times it will not.

However I can allow users to add custom CSS to the header section of each
rendered page, so if people are willing to customize it, they are free to
do so then. It will also then be your own responsibility to include Google
Fonts (which I will not support by default due to the selfhosted community
philosophy). But allowing users to add custom code to the head section, you
can add fonts or even scripts if you want to. I will create a separate
issue for that purpose.

**Comment by kaleben0** [comment]
Yeah, I understand that. I modified one of the themes and switched it to Google Font's "Quicksand" and it looks really nice, but I can see how the spacing changed.

**Comment by danielbrendel** [comment]
No worries. Also the custom code for the page head section will be worked on via #291
