### ISSUE TITLE
Share images from selfhosted instance

### ISSUE THREAD

**Issue by dghoti** [danielbrendel/hortusfox-web#307]
**Description of your request**
Loving the program so far! but as I host my own instance and (ok - Im lazy) I have not set up the SMTP server - I was wondering if it would be possible to share the pictures directly from my own instance - this seems to be possible, as I can set my own URL, and the dialog says it is sharing on my instance - but I do not get a link (like is shown in the tutorial video [https://youtu.be/prvFQUWtp30]]

**Describe the solution you'd like**
Click share on a picture/set of pictures and receive a link to pass via social media etc...

**Describe alternatives you've considered**
Saves having to post pictures elsewhere - eg google photos

**Additional context**
currently when clicking the share button, I just get "undefined"
![image](https://github.com/user-attachments/assets/f550216d-a1cf-4864-8a59-f5c3f3f1341f) 

![image](https://github.com/user-attachments/assets/d00df7f9-d0d3-45d2-a951-8bba69ec1581)
(I have set the full domain of the self hosted instance in the config(am hosting several other apps on this domain sucessfully:
![image](https://github.com/user-attachments/assets/0382c350-97b3-4ab0-bf51-70d165b7b7ec)

**Comment by danielbrendel** [comment]
Hi, in order to use your own backend to receive shared images, you'll need
to implement that functionality by yourself. This is pretty undocumented,
so until there is no documentation yet, you'll need to check out the source
here:
https://github.com/danielbrendel/hortusfox-com/blob/main/app/controller/api.php
Basically you'll need to catch POST requests to `/api/photo/share` on your
backend.
Hope this helps for now.

**Comment by danielbrendel** [comment]
Here is a document explaining the requirements of your own backend system: https://hortusfox.github.io/sharing.html

**Comment by dghoti** [comment]
Thank you
